version: "3.8"

services:
  db:
    image: postgres:15
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    # NO ports -> no se mapea al host en CI
    volumes:
      - pgdata_ci:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    # No montamos el repositorio desde el host: la imagen ya contiene el código (COPY . /app en Dockerfile)
    # Evitamos 'volumes' para no interferir con el host
    command: python run.py
    # No exponemos puertos en CI (no necesarios para ejecutar tests)

volumes:
  pgdata_ci:
